import * as React from "react"
import { Partytown } from '@builder.io/partytown/react';

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      rel="preload"
      href="/fonts/NunitoSans-Black.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansBlack"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-BlackItalic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansBlackItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-Bold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansBold"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-BoldItalic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansBoldItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-ExtraBold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansExtraBold"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-ExtraBoldItalic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansExtraBoldItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-ExtraLight.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansExtraLight"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-ExtraLightItalic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansExtraLightItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-Italic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-Light.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansLight"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-SemiBold.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansSemiBold"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-SemiBoldItalic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansSemiBoldItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-LightItalic.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansLightItalic"
    />,
    <link
      rel="preload"
      href="/fonts/NunitoSans-Regular.ttf"
      as="font"
      type="font/ttf"
      crossOrigin="anonymous"
      key="nunitoSansRegular"
    />,
    <Partytown key="partytown" forward={['gtag', 'dataLayer.push']} />,
    <script key="google-analytics" type="text/partytown" src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GTAG}`} />,
    <script
      key="google-analytics-config"
      type="text/partytown"
      dangerouslySetInnerHTML={{
        __html: `window.dataLayer = window.dataLayer || [];
        window.gtag = function gtag(){ window.dataLayer.push(arguments);}
        gtag('js', new Date()); 
        gtag('config', '${process.env.GTAG}', { send_page_view: false })`
      }}
    />
  ])
}
